# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lLOa6LW0b0l3X0JaNkTrSv3cRPay0YtJ
"""

# This program prints Hello, world!

print('Hello, world!')